spring:
  application:
    name: repo-identity-api
  datasource:
    url: jdbc:mysql://localhost:3306/lms_identity_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: sa
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
#      password: redis_password
  kafka:
    bootstrap-servers: localhost:9092
  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:REDACTED_EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD:REDACTED_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: ${SERVER_PORT:8081}

security:
  jwt:
    public-key-path: file:secrets/jwt-public.pem
    private-key-path: file:secrets/jwt-private.pem
    issuer: repo-identity
    access-ttl: PT10M
    refresh-ttl: P7D

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:REDACTED_GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET:REDACTED_GOOGLE_SECRET}

# Application Configuration
app:
  email:
    from: ${EMAIL_FROM:noreply@hocba.com}
    from-name: ${EMAIL_FROM_NAME:Hệ Thống Học Bá}
  frontend:
#    url: ${FRONTEND_URL:http://localhost:3000}
     url: ${FRONTEND_URL:https://lms.dangch.tech}

cms:
  base-url: ${CMS_BASE_URL:https://cms.dangch.tech}
  webclient:
    max-in-memory-mb: 16

