spring:
  application:
    name: repo-multimedia

  datasource:
    url: jdbc:mysql://localhost:3306/lms_media_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
server:
  port: ${SERVER_PORT:8091}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: repo-multimedia
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.lms.multimedia: INFO
    org.springframework.web: INFO

security:
  jwt:
    public-key-path: file:secrets/jwt-public.pem

services:
  multimedia-service:
    container_name: repo-multimedia
    image: repo-multimedia
    ports:
      - "8086:8086"
    networks:
      - shared-network

  networks:
    shared-network:
      external: true

