spring:
  application:
    name: repo-multimedia

  datasource:
    url: jdbc:mysql://localhost:3306/lms_media_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  kafka:
    consumer:
      group-id: multimedia-group

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: ${SERVER_PORT:8091}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: repo-multimedia
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.lms.multimedia: INFO
    org.springframework.web: INFO

security:
  jwt:
    public-key-path: file:secrets/jwt-public.pem


kafka:
  topics:
    file: storage.file.commit

storage:
  presign-ttl: PT15M
  pending-ttl: PT12H
  cleanup-cron: "0 0 * * * *"
  delete-object-on-soft-delete: true
  minio:

  #    local
#    endpoint: ${MINIO_ENDPOINT:http://localhost:49000}
#    console-endpoint: ${MINIO_CONSOLE:http://localhost:49001}

  #    prod
    endpoint: ${MINIO_ENDPOINT:http://lms-video-minio:9000}
    console-endpoint: ${MINIO_CONSOLE:http://lms-video-minio:9001}

    access-key: ${MINIO_ROOT_USER:minioadmin}
    secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
    bucket: ${MINIO_BUCKET:videos}
    image-bucket: ${STORAGE_MINIO_IMAGE_BUCKET:images}
    audio-bucket: ${STORAGE_MINIO_AUDIO_BUCKET:audios}
    region:
