version: '3.8'

services:
  repo-payment:
    build:
      context: ..
      dockerfile: repo-payment/Dockerfile
    container_name: repo-payment
    ports:
      - "8079:8079"
    environment:
      - SERVER_PORT=8079
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/lms_payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka
      - SECURITY_JWT_PUBLIC_KEY_PATH=file:secrets/jwt-public.pem
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../secrets:/app/secrets
    restart: unless-stopped
