spring:
  application:
    name: repo-identity-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/lms_identity_db
      # Hoặc dùng cấu hình chi tiết:
      # host: localhost
      # port: 27017
      # database: lms_identity_db
      # username: mongodb_user
      # password: mongodb_password
      # authentication-database: admin
    redis:
      host: localhost
      port: 6379
#      password: redis_password
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

security:
  jwt:
    public-key-path: file:secrets/jwt-public.pem
    private-key-path: file:secrets/jwt-private.pem
    issuer: repo-identity
    access-ttl: PT5M
    refresh-ttl: P7D

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:469580312924-htqo2ul0k5ch38d6ot64csnii2cabr7q.apps.googleusercontent.com}
    client-secret: ${GOOGLE_CLIENT_SECRET:REDACTED_GOOGLE_SECRET}
