version: '3.8'

services:
  repo-listening-practice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repo-listening-practice
    ports:
      - "8089:8089"
    environment:
      - SERVER_PORT=8089
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/lms_listening_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
