spring:
  application:
    name: repo-payment
  kafka:
  #   prod
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:lms-kafka:9092}
  #  local
    # bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/lms_payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

notification:
  publisher:
    topic: ${NOTIFICATION_TOPIC:notification.events}

server:
  port: 8079

security:
  jwt:
    public-key-path: file:secrets/jwt-public.pem

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: INFO
    com.lms.payment: DEBUG
    org.hibernate.SQL: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

payos:
  client-id: ${PAYOS_CLIENT_ID:REDACTED_PAYOS_CLIENT_ID_DEV}
  api-key: ${PAYOS_API_KEY:REDACTED_PAYOS_API_KEY_DEV}
  checksum-key: ${PAYOS_CHECKSUM_KEY:REDACTED_PAYOS_CHECKSUM_DEV}
#  local
  # return-url: ${PAYOS_RETURN_URL:http://localhost:3000/payment/success}
  # cancel-url: ${PAYOS_CANCEL_URL:http://localhost:3000/payment/cancel}
#  prod
  return-url: ${PAYOS_RETURN_URL:https://lms.dangch.tech/payment/success}
  cancel-url: ${PAYOS_CANCEL_URL:https://lms.dangch.tech/payment/cancel}