spring:
  application:
    name: repo-quiz
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  datasource:
    url: jdbc:mysql://localhost:3306/lms_quiz_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

server:
  port: ${SERVER_PORT:8093}

security:
  jwt:
    public-key-path: file:secrets/jwt-public.pem
    issuer: repo-identity-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: INFO
    com.lms.quiz: DEBUG
    org.hibernate.SQL: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

quiz:
  progress:
    kafka:
      topic: ${QUIZ_PROGRESS_KAFKA_TOPIC:quiz.progress.events}
